config/routes.rb
Rails.application.routes.draw do
  # resources :madlibs
  # resources :categories
  # resources :words
  # resources :pranks
  # resources :users

   root 'pranks#home', as: 'home'

   get '/index' => 'categories#index', as: 'category_index'

   get '/witches_new'  => 'madlibs#new_witch', as: 'witches_new'
  post '/witches_create' => 'madlibs#create_witch', as: 'witches_create'
  get '/witches_show/:id' => 'madlibs#show_witch', as: 'witches_show'

  get '/ghosts_new'  => 'madlibs#new_ghost', as: 'ghosts_new'
 post '/ghosts_create' => 'madlibs#create_ghost', as: 'ghosts_create'
 get '/ghosts_show/:id' => 'madlibs#show_ghost', as: 'ghosts_show'

 get '/dolls_new'  => 'madlibs#new_doll', as: 'dolls_new'
  post '/dolls_create' => 'madlibs#create_doll', as: 'dolls_create'
  get '/dolls_show/:id' => 'madlibs#show_doll', as: 'dolls_show'

  get '/sk_new'  => 'madlibs#new_sk', as: 'sk_new'
  post '/sk_create' => 'madlibs#create_sk', as: 'sk_create'
  get '/sk_show/:id' => 'madlibs#show_sk', as: 'sk_show'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prank.rb
class Prank < ApplicationRecord
  has_many :madlibs
  has_many :categories, through: :madlibs
end

app/controllers/pranks_controller.rb
class PranksController < ApplicationController

  def home

  end
  
end

app/helpers/pranks_helper.rb
module PranksHelper
end

app/views/pranks/home.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>

<body class="home-body-color">


<h1 class="fright-title shadow-pop-br">WELCOME TO FRIGHT-<span class= "text-flicker-in-glow madlib-word">O-MATIC!</span></h1>

<div class="text-shadow-pop-top">
<div class="row">
    <div class="col s12 m6">
      <div class="card black darken-1 shadow-pop-br">
        <div class="card-content white-text">
          <span class="card-title">PLAY THE GAME IF YOU DARE...</span>
          <p class="animated flash slow category-button">CLICK 'CATEGORIES' TO BEGIN
          </p>
        </div>
        <div class="card-action">
        </div>
        </div>
      </div>
    </div>
  </div>

<div class="img-holder shadow-pop-br">
  <img src="assets/halloween_2.jpg" id="pumpkin" alt="smoking pumpkin">
</div>

<div>
<a><%= link_to "CATEGORIES", category_index_path, class: 'waves-effect waves-light btn-large dark grey src-link text-blur-out'%></a>
</div>

</body>

</html>