config/routes.rb
Rails.application.routes.draw do
  # resources :madlibs
  # resources :categories
  # resources :words
  # resources :pranks
  # resources :users

   root 'pranks#home', as: 'home'

   get '/index' => 'categories#index', as: 'category_index'

   get '/witches_new'  => 'madlibs#new_witch', as: 'witches_new'
  post '/witches_create' => 'madlibs#create_witch', as: 'witches_create'
  get '/witches_show/:id' => 'madlibs#show_witch', as: 'witches_show'

  get '/ghosts_new'  => 'madlibs#new_ghost', as: 'ghosts_new'
 post '/ghosts_create' => 'madlibs#create_ghost', as: 'ghosts_create'
 get '/ghosts_show/:id' => 'madlibs#show_ghost', as: 'ghosts_show'

 get '/dolls_new'  => 'madlibs#new_doll', as: 'dolls_new'
  post '/dolls_create' => 'madlibs#create_doll', as: 'dolls_create'
  get '/dolls_show/:id' => 'madlibs#show_doll', as: 'dolls_show'

  get '/sk_new'  => 'madlibs#new_sk', as: 'sk_new'
  post '/sk_create' => 'madlibs#create_sk', as: 'sk_create'
  get '/sk_show/:id' => 'madlibs#show_sk', as: 'sk_show'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :madlibs
  has_many :pranks, through: :madlibs
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.erb
<body>

<h1 class="animated fadeOut title">ALMOST THERE</h1>

<div class="question-styling">

<h2 class="question-title text-shadow-pop-bottom">CHOOSE A CATEGORY TO PROCEED</h2>
</div>

<div class="column-color text-shadow-pop-bottom">
 <div class="row">
   <div class="col s12 m6">
     <div class="card">
       <div class="card-image">
         <img src="assets/witch_image.jpg">
         <!-- <span class="card-title animated shake category-button">MEOW</span> -->
         <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a> -->
       </div>
       <div class="card-content">
         <a><%= link_to "WITCHES", witches_new_path, class: 'waves-effect waves-light black btn'%></a>
       </div>
     </div>
   </div>
 </div>
</div>


<div class="column-color text-shadow-pop-bottom">
 <div class="row">
   <div class="col s12 m6">
     <div class="card">
       <div class="card-image">
         <img src="assets/ghost_image.jpg">
         <!-- <span class="card-title animated shake category-button">BOO</span> -->
         <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a> -->
       </div>
       <div class="card-content">
         <a><%= link_to "GHOSTS", ghosts_new_path, class: 'waves-effect waves-light black btn' %></a>
       </div>
     </div>
   </div>
  </div>
 </div>

<div class="column-color text-shadow-pop-bottom">
 <div class="row">
   <div class="col s12 m6">
     <div class="card">
       <div class="card-image">
         <img src="assets/doll_image.jpg">
         <!-- <span class="card-title">HELLO PRETTY</span> -->
         <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a> -->
       </div>
       <div class="card-content">
         <a><%= link_to "DOLLS", dolls_new_path, class: 'waves-effect waves-light black btn' %></a>
       </div>
     </div>
   </div>
  </div>
 </div>

<div class="column-color text-shadow-pop-bottom">
 <div class="row">
   <div class="col s12 m6">
     <div class="card">
       <div class="card-image">
         <img src="assets/bones_image.jpg">
         <!-- <span class="card-title">Card Title</span> -->
         <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a> -->
       </div>
       <div class="card-content">
         <a><%= link_to "SERIAL KILLERS", sk_new_path, class: 'waves-effect waves-light black btn' %></a>
       </div>
     </div>
   </div>
  </div>
 </div>
</body>